# ---- GENERAL CONFIG ----
spring.application.name=integrations-service
server.port=8080
server.forward-headers-strategy=framework
logging.file.name=logs/Integrations.log
build.version=@project.version@
server.servlet.context-path=/integrations
server.url=http://localhost:8080
excite.url=http://db2023/excite/pmws.dll/
server.error.include-message=always
server.error.include-stacktrace=never
bugsnag.release-stage=development
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
management.endpoints.web.exposure.include=health,prometheus

# ---- DATABASE ----
spring.datasource.url=jdbc:sqlserver://db2023;database=GitekXLite;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Excite2022$
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.validation-timeout=300000

# JPA
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.proc.param_null_passing=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# AUTH
keycloak.signature.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu/6u3SRkTsYQ9BvJWW/k5h5YHHXrQbxWsXt6S890TICteMazjJb95jdsvkQhw5Y8O7IeGTQrFRvbNDkdkcr9f3qGiQw5G/PrXhSYDMfeNVnPijthFOirdBafejFunzT+GeEjDsi15+E0YgbV1lHaSi0Lwh/4lRbqqyjNe0QY8+JjCyklKVG1z/06l/KLd2SGTL/LYFnFl2W+yN42Y2fjgnocV3ROU8zB5s+HPtBaU2OWCFFYIqNu4mzg0iqgnuh7SrxTF2lFBKBq0q+JfhyD5f0d2WnDNx9g8rpaIjsBCix9ZlU2pzsHsbiFoHtxcihQzlC2zeEM7ocX/8IBVzDDjwIDAQAB
