# ---- GENERAL CONFIG ----
server.url=https://api.excite.cx
excite.url=https://excite.cx/
bugsnag.release-stage=production

# ---- DATABASE ----
spring.datasource.url=jdbc:sqlserver://195.204.97.50;database=GitekXLite;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Gitek2015!

# AUTH
keycloak.signature.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxtmHn1AMosT0LNVF2peT/j90tg2plrMhNoaqrFri1a86cJrGuSCubqPgijn2dq+r82SqglNNWQbiSUo/o2OURbik3gPUqAFq25zzU4BG6nMf+Wu0pz7GUWF+rlFkQqPpYpWHsetFW0RdMHh7r6VeobBJ3dpQbiNHtW0Uaki3WnYN6cDmK+fQaH1lBc5IOyBnApbR/AxflH9IRnEfzIUnJoT0VtYmBdnQNzI/eZ3SSGzmzpSnA6fB1P3WZHQZGI8wIklowIfou0hKUU3Yo8v/0JqPQDkcx1TzBC1TxSAEOQMN8MfwAd0VIGW4MSPYIbl5XY+lbUpT1T8IklJRL35EZwIDAQAB
