# ---- GENERAL CONFIG ----
server.url=https://excitedemo.cx
excite.url=https://asp.gitek.no/gxldemo/pmws.dll/
bugsnag.release-stage=staging

# ---- DATABASE ----
spring.datasource.url=jdbc:sqlserver://195.204.97.50;database=GitekXLiteDemo;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Gitek2015!

# AUTH
keycloak.signature.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu/6u3SRkTsYQ9BvJWW/k5h5YHHXrQbxWsXt6S890TICteMazjJb95jdsvkQhw5Y8O7IeGTQrFRvbNDkdkcr9f3qGiQw5G/PrXhSYDMfeNVnPijthFOirdBafejFunzT+GeEjDsi15+E0YgbV1lHaSi0Lwh/4lRbqqyjNe0QY8+JjCyklKVG1z/06l/KLd2SGTL/LYFnFl2W+yN42Y2fjgnocV3ROU8zB5s+HPtBaU2OWCFFYIqNu4mzg0iqgnuh7SrxTF2lFBKBq0q+JfhyD5f0d2WnDNx9g8rpaIjsBCix9ZlU2pzsHsbiFoHtxcihQzlC2zeEM7ocX/8IBVzDDjwIDAQAB

